kind: ConfigMap 
apiVersion: v1 
metadata:
  name: grafana-datasource
data:
  datasource.yaml: | 
    apiVersion: 1
    datasources:
      - name: myinfluxdb
        type: influxdb
        access: proxy
        database: k6
        url: http://influxdb:8086
        isDefault: true
